### ISSUE TITLE
this work with meters - digital or non-digital?

### ISSUE THREAD

**Issue by Barceloch** [JonasMock/EnergyMonitoring_Tensorflow_Model#1]
I friend, interesting your solution, I have this cuestion: 
https://www.reddit.com/r/computervision/comments/lkqxbx/how_get_digits_recognize_from_electric_meter_with/

and I get this suggets:
"You can try tensorflow lite. Take a pretrained mnist model. And divide your photo such that there is one digit in every cropped image"

Your think that I can use your model for my case?

**Comment by jonasmock** [comment]
Yes, of course you can use it. However, the numbers are not recognized automatically. Currently, a crop area is defined manually in the configuration file where the corresponding number is located. In my use case, the camera always photographed the electricity meter from the same position, so automatic detection was not necessary for me. These scripts can also be helpful to classify the images manually. As for your use case, there are certainly better ways to implement it. I wrote this code at the beginning of my studies, today I would probably build it a bit differently. 

As for the trained model, I'd recommend trying it with an MNIST dataset (e.g. https://www.tensorflow.org/quantum/tutorials/mnist) or manually classifying some of your images of the electricity meter if necessary. My model is probably only fit to my data set, unfortunately. Also, I didn't use any data augmentation methods at the time. The model in the repository is only based on a few thousand images specifically from my use case.

**Comment by Barceloch** [comment]
thank for your answer,  It will be really helpfull, I am looking for and reading various things the problem is that I am from Cuba and I have internet limitations and it is more complicated.

thank for you suggets...
